management.tracing.sampling.probability=1.0

management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces

management.otlp.metrics.export.enabled=false

#Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

server.port = 8080
jwt.secret=ThisIsMySuperSecretKeyForJwtAuthentication123456789

logging.level.org.springframework.cloud.gateway=TRACE

#spring.cloud.gateway.server.webmvc.routes[0].id=ticket-service
#spring.cloud.gateway.server.webmvc.routes[0].uri=lb://TICKET-SERVICE
#spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/tickets/**

resilience4j.ratelimiter.instances.ticketService.limit-for-period=5
resilience4j.ratelimiter.instances.ticketService.limit-refresh-period=10s
resilience4j.ratelimiter.instances.ticketService.timeout-duration=0
